### ISSUE TITLE
Start Delay

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#10]
Would like to be able to pick a start delay after clicking on a lesson and before the lesson actually starts of 1 to 3 seconds.

**Comment by RandyLoeb** [comment]
PRESPACE lets user add "silence" to the start of the very first word, measured in seconds. This was requested for some sound systems that need to "woken up" like bluetooth headsets.  But e.g. if you set it to 3, you shouldn't hear anything for 3 seconds after hitting play.

**Comment by nolleto1** [comment]
Got it

**Comment by RandyLoeb** [comment]
@nolleto1 if it suits the need good, feel free to close out the issue.
