### ISSUE TITLE
The volume of VOICE is too soft

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#100]
Not really a bug but when I was going over the program with Glenn, he said he was having trouble hearing the voice.  He has some hearing issues and I assume some of our other students will to based on their age.  Can you increase the volume so that the present volume corresponds to 5 and it can be made louder if needed?

**Comment by RandyLoeb** [comment]
voice and morse have independent volume controls....has he tried maxing it out to 10? 
![image](https://user-images.githubusercontent.com/34562250/173253344-1a2cb33a-d282-482a-943e-67d5a455e43a.png)

**Comment by RandyLoeb** [comment]
@nolleto1 also aside from the voice volume setting, maybe try different voices. to me the female voices seem quieter than the male options.

**Comment by RandyLoeb** [comment]
I did a little research and I'm not sure there is anything I can do to drive the speech volume more. Another option is if someone pre-recorded the speech to mp3 files, we could probably just play those in the browser and can probably get those louder if needed, quite a bit of work though.
