### ISSUE TITLE
Shuffle not working right

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#102]
From Mike:
If you select Shuffle and subsequently change the lesson, Shuffle remains selected.  When you subsequently deselect Shuffle, the trainer reverts back to the originally shuffled lesson.

(1) Please ask Randy to have Shuffle automatically deselected every time a lesson is changed, or Regenerate Drill is selected.

Here is a link to Glenn's video showing the problem.

(https://drive.google.com/file/d/18oScKhC7LfF-tWsfJNRRTMEirc90Cj6I/view?usp=sharing)

**Comment by RandyLoeb** [comment]
On /dev/ I've made it so while in the shuffled state (i.e. button says "unshuffle"), if anything changes the button will revert to its unshuffled state (i.e. button says "shuffle").

**Comment by nolleto1** [comment]
Works like you say so I'll close this.
