### ISSUE TITLE
Make state abbreviations say the actual state when voice is on

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#103]
Per Mike:
Glenn would like States and QSO Abbreviations to voice the actual meaning instead of the letters e.g., TN would be voiced as “Tennessee.”  I know we discussed this with Randy at one time, but I don’t recall the solution.  I believe Randy said we would need to come up with a special character that would tell the trainer to voice differently.  This is not a top priority, but I would like it in the queue.

**Comment by RandyLoeb** [comment]
Assigning to @MikePadron / @LongIslandCW  to fill in the json

**Comment by nolleto1** [comment]
Just tried running the states for KMY.  They work fine with voice OFF but with voice ON, there is no voice heard and they jump erratically to the next set.

**Comment by nolleto1** [comment]
OK, I just went back to verify that the voice time was working properly and I got all the states that I didn't get above plus some other words.  Some sort of cache isn't emptying?

**Comment by nolleto1** [comment]
Works OK now.
Thanks.
