### ISSUE TITLE
Make "Smoothing" a default and hide

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#107]
We would like to take all the "Smoothing" settings out of the Settings accordion and just make them the default.  No need for us to be able to change any of them.

**Comment by RandyLoeb** [comment]
@nolleto1 detailed smoothing controls hidden on /dev/

**Comment by nolleto1** [comment]
Randy,  Please go ahead and hide the "Smoothing" tab also.  No need for us to see it as we don't want to not smooth the sound.

**Comment by RandyLoeb** [comment]
@nolleto1 smoothing button now hidden on /dev/

**Comment by nolleto1** [comment]
Perfect.  Thanks
