### ISSUE TITLE
WORD SPACE  is confusing

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#109]
The way WORD SPACE is used is very confusing.  Mike says he only really needs word spacing of 1,2,3 and 4 times the normal spacing. Can you change this so 1 is the default with no additional word spacing and then 2,3, and 4 would correspond to twice, thrice, and 4x normal spacing?

**Comment by RandyLoeb** [comment]
@nolleto1 should work as described on /dev/

**Comment by nolleto1** [comment]
Looks good.
Thanks Randy
