### ISSUE TITLE
Issue with Inserting a File

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#111]
When you insert a file, it will work OK but if you want to make any changes and then click on "APPLY" it reverts back to the last lesson plan because it is still highlighted.  Can clicking on Insert File clear the lesson plan set up?

**Comment by RandyLoeb** [comment]
@nolleto1 on /dev/ inserting a file should now unselect the licw lesson and thereby disable apply until a lesson is selected

**Comment by nolleto1** [comment]
Works fine now.
