### ISSUE TITLE
Input default change

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#116]
Randy,
Can you please set the default input block to "hide"?  I think this would be more appropriate since we don't want the students to see the characters most of the time.

Also, Have you made any significant changes in DEV  from all the work you and Glenn were doing?  If so, is it time to do an update to Main?

Thanks,
Tom

**Comment by RandyLoeb** [comment]
text is now hidden when page loads

**Comment by nolleto1** [comment]
Thanks Randy.
