### ISSUE TITLE
iPad Launch when Off Line

### ISSUE THREAD

**Issue by AC3DSCOTT** [LongIslandCW/morsebrowser#124]
I downloaded the .zip file and unloaded it in my :Files: app on the iPad Pro.  I placed the file on the iPad ( rather than in the cloud!!). When i click the index, all that is loading/showing is text no graphics.   This is not in my wheelhouse of knowledge so I dont know what I am not doing!!  Here is what I see

![6064F953-AA60-462B-B826-BFA27780E45F](https://user-images.githubusercontent.com/110058181/181085937-f9eb270c-a555-4beb-b1e2-88e569b30a83.png)

Thanks. Scott - AC3D

**Comment by RandyLoeb** [comment]
@AC3DSCOTT possibly ipad doesn't allow javascript when loaded locally (that is the case on newer android devices, so a local web server has to be running on the phone). There are some solutions described on this page you might try: https://stackoverflow.com/questions/6298420/can-i-run-html-javascript-files-in-ipad   if you do please let us know if you got it working.
