### ISSUE TITLE
Upgrade to fully support Firefox

### ISSUE THREAD

**Issue by brock** [LongIslandCW/morsebrowser#129]
Was in the beginner course tonight and noticed Dave (VK5PL) demonstrate this site and he pointed out how it doesn't work well with Firefox.

In particular, the buttons didn't pre-fill and the activity indicators were regularly spinning when landing on the page for the first time.

I'm not sure that I'm the man for the job, since I haven't done front-end in a while, but I'll dig through the code after posting this and see if it looks like something I can tackle. Mainly just wanting to record this for future upgrades.

**Comment by RandyLoeb** [comment]
@brock we don't have the resources now to support firefox

**Comment by RandyLoeb** [comment]
see above
