### ISSUE TITLE
Farnsworth not working right

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#13]
Example:  If I select 20 wpm and 5 fwpm, the code is being sent at about 5 wpm not 20 wpm character speed.

**Comment by RandyLoeb** [comment]
Hmm...I confirm. Actually the problem starts at anything less than 10. i.e. 20/10 sounds fine but 20/9 is where it drops off the table.  Phillips site doesn't have that problem, so probably something I'm doing. I'll look into.

**Comment by RandyLoeb** [comment]
@nolleto1 should be fixed now on /dev/  site, please retest and let me know.

**Comment by nolleto1** [comment]
Still not working when I just tested it.
