### ISSUE TITLE
Chipmunk says 'hi'

### ISSUE THREAD

**Issue by abeyer** [LongIslandCW/morsebrowser#134]
**Describe the bug**
(On a meta-note: This is both the most ridiculous issue title I've ever written, but also the most succinct and accurate description of the issue) Every time I press play, shortly after starting (typically during the prespace, but overlapping with the output if prespace is/near 0) I hear a bit of audio glitch that sounds like a sped-up voice ("chipmunk" voice) saying "hi"

I _think_ this didn't happen when I first used the site, but it seems to repro 100% for me now, even after clearing cookies/data to reset any preferences.

**To Reproduce**
1. Load the page
2. Press play

**Expected behavior**
No chipmunks harmed in the making of this cw.

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome
 - Version 105.0.5195.134 (Official Build) (64-bit) 

**Additional context**
This may be related to the voice synth features. It happens for me with or without voice enabled, but enabling voice and then changing the voice selected seems to affect the sound produced.

**Comment by abeyer** [comment]
Correction, apparently the chipmunk is just saying "i"

This seems to be an issue with the `primeThePump` function here https://github.com/LongIslandCW/morsebrowser/blob/561423ba89084cf3534e9eb6713baa3c58757609/src/morse/voice/MorseVoice.ts#L186 which the comment suggests is to address some problem in safari https://github.com/LongIslandCW/morsebrowser/blob/561423ba89084cf3534e9eb6713baa3c58757609/src/morse/morse.ts#L358

**Comment by RandyLoeb** [comment]
@abeyer is this still an issue?

**Comment by abeyer** [comment]
Sorry, I'd kinda fallen out of CW practice and lost track of this for a long time... but this has continued to be an issue which seems like it should be addressed. (would be nice to fix upstream too, as this seems to be a bug on their part, but I don't have any connections to get a bug report in ChromeOS actually looked at and not just disappearing into the black hole of Google's "feedback" box.)

Would ask if we could reopen this.
