### ISSUE TITLE
Selecting new speed is slow

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#14]
There is a delay between when I select a new speed and when it actually takes place.  Seems to be more than just completing the groups but maybe not.

**Comment by RandyLoeb** [comment]
It should take effect immediately with the next played word, but not during a word currently playing....let me know if that is not the case.

**Comment by R120** [comment]
I'm testing at 20 WPM... Seems nicely responsive at this speed. Also REALLY appreciate that I can direct enter a number as an alternative to loads of up/down arrows.

**Comment by nolleto1** [comment]
Works fine now that the Farnsworth issue was corrected.
