### ISSUE TITLE
Place a black line under the last set of cards

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#144]
This was a request by one student who evidently couldn't figure out that he needed to use the tab on the side of the window to scroll down to the bottom of the page.  Since it's not easy, let's forget it.

**Comment by RandyLoeb** [comment]
@nolleto1 it would be easy to make the last card a different color...

**Comment by RandyLoeb** [comment]
@nolleto1 on /dev/ last card is red. let me know

**Comment by nolleto1** [comment]
Perfect!
