### ISSUE TITLE
"Tuning button"

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#147]
We would like to be able to send a constant tone so the people using the haptic machine can set the frequency.

**Comment by RandyLoeb** [comment]
@nolleto1 On /dev/ if you go to where the dit tone frequency is set, and just click once on the "dit" label, it will play that tone for 10 seconds. Let me know if the user interface needs to be something different, etc.

**Comment by nolleto1** [comment]
This is now solved with the new tuning button.
