### ISSUE TITLE
Voice Recap not working right

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#159]
If I don't click on Voice Recap and then shuffle the cards and then click on Voice Recap, I get the previous one set spoken.

Same thing happens if I don't click on Voice Recap at the end of an exercise and then go to another exercise and click Voice Recap after playing it I get the previous letters. 

Tom

**Comment by RandyLoeb** [comment]
@nolleto1 i believe pressing "play" clears the voice recap buffer. don't see this as a serious problem as shouldn't really use voice recap until after play has been pressed?

**Comment by nolleto1** [comment]
I've used Pause and stopped and also just used just stop and had the same
issues.  It's always when play is pressed that it happens.  It seems like
the buffer isn't getting cleared.  Also, note the issue with the cards
speaking twice after the first card.

I'm headed out to my club meeting now but let me know if I need to send
more specific details and I'll put something together tomorrow.

Tom
