### ISSUE TITLE
XTRAWRDSPDITS

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#16]
I would think that XTRAWRDSPDITS is the same as what we think of as Farnsworth.  Actual speed should be the character speed and the Farnsworth speed adds extra space between characters and words.

**Comment by RandyLoeb** [comment]
That's not what it does currently. If XTRAWRDSPDITS is 0, it does nothing. Every increment adds 1 "farnsworth unit" of time to the existing word spacing. By default word spacing is 7 farnsworth units. So if you wanted to double the word spacing, set XTRA to 7, i.e. add another 7 units. I think this is called "wordsworth"? https://pypi.org/project/wordsworth/
as to what i mean by unit or farnsworth unit, see Phillips:https://morsecode.world/international/timing.html

**Comment by nolleto1** [comment]
OK.  I'll check that out.
Tom
