### ISSUE TITLE
Group size

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#17]
We really don't need a min and max on group size.  Just be able to pick from 1 to 5 characters per group.  Unless you need it for programming purposes.

**Comment by RandyLoeb** [comment]
I like it so that word size can be randomized.
What I can do as compromise is add some kind of toggle so that by default they'll be synchronized size, or alternatively just show wordsize, with some toggle to expose the finer min/max options, something like that.

**Comment by nolleto1** [comment]
OK.  Let's go with by default there synchronized with a toggle to expose
the min/max options.
Tom

**Comment by RandyLoeb** [comment]
@nolleto1 by default now the min/max are synchronized, i.e. if user toggles "Override Size" button, only min is enabled and will change both min and max. next to override size there's a "Sync Size" button that user can toggle whether to enable max, so they can then set min and max independently. try on /dev/ and let me know please.

**Comment by nolleto1** [comment]
Works fine.
