### ISSUE TITLE
Rewind

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#18]
Can we just have it restart if we hit play instead of needing to rewind after it completes the file or we hit STOP?

**Comment by RandyLoeb** [comment]
1. I can have it automatically do full rewind when it hits the end.
2. I can have STOP do the same full rewind, but I would then like to add a PAUSE which wouldn't rewind.

Let me know if that sounds good, should be easy.

**Comment by nolleto1** [comment]
That should work.
Tom

**Comment by RandyLoeb** [comment]
@nolleto1 this should be working on /dev/ now, please test and let me know.

**Comment by nolleto1** [comment]
Works fine.
