### ISSUE TITLE
We have a rock star in our midst... wave shaped CW tones. Yeah!

### ISSUE THREAD

**Issue by R120** [LongIslandCW/morsebrowser#22]
OK... I have picky ears I get it. Not a fan of clicks and thumps in my CW training. 

Absolutely LOVE the envelope shaped CW tones... No clicks. No thumps.

I can think of several other Windows based programs that fall short in this respect.

Well done!

**Comment by RandyLoeb** [comment]
thank SG Phillips. closing out this issue.
