### ISSUE TITLE
Double click on word list to resume play at the selected word.

### ISSUE THREAD

**Issue by R120** [LongIslandCW/morsebrowser#23]
Seems limited to have back/forward 1 and full back/forward.

What if I want to go back 13 words?

R120 = Bob WO6W

**Comment by RandyLoeb** [comment]
@R120 double-click on /dev/ should now make that word the current word. don't think tablet/phone users can do it but should work with a mouse. let me know.

**Comment by nolleto1** [comment]
Maybe I'm not understanding this right but it doesn't go back to the word I click.  However, it will let me hit BACK 1 as many times as I want so that may be OK.  Please check with Bob.

**Comment by RandyLoeb** [comment]
Are you double-clicking?

**Comment by nolleto1** [comment]
Nope.  Missed that.  Sorry.
