### ISSUE TITLE
Background color changing

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#36]
I am finding it confusing when the background color of the "Randomize", "Override Time", etc. buttons change color when you scroll over them when they are turned "off".  Can they not change when you scroll over them or is this something that just happens when they get the focus?  It would be nice if they didn't change until you went from on to off or off to on.

**Comment by RandyLoeb** [comment]
@nolleto1 on next /dev/ reload you should see icons (circle or check) that hopefully will dispel confusion. it is something that the bootstrap library does out of the box, would take some time to figure it out. Hopefully the icon visual cue will be good enough for now.

**Comment by nolleto1** [comment]
That look great.  Solves the problem.
Thanks Randy!
