### ISSUE TITLE
Functionality we would like to see in the New Player.

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#7]
Functionality we would like to see in the New Player.

G4FON:

1) General Settings 	
	- Effective Speed should be set to "Each character" always
	- Would like to be able to set the Session Length in Minutes from 1 to 15
	- Need to be able to select a starting delay in seconds

2) Main Screen Settings
	- Show a session Time
	- Be able to select the pitch
	- Be able to select the Actual Speed from 1 to 50
	- Be able to select the Effective Speed from 1 to 50 in increments of 1
	- Will need Start/Play and Stop buttons

3) Other
 	- It would be nice to have tabs to go directly to some Word, Phrases, and QSO files based on the 	letters selected and have them play in random order.

CW_Player

1) Under Random
	- We would like to be able to have a list of files associated with each session similar to the way 	  	these are presented but just show those files for each session (A-F).
	- Be able to type in whatever letters we want at the top and have them play randomly
	- This would probably be associated with the group function but we would like to be able to 	play just one letter repeatedly. 

Other Functionality

1) Select a file and run it at a selected speed for a selected time.

2) Type in a number of random characters and be able to change the speed manually from the top speed (no Farnsworth) to 5 wpm on the go.

3) Select random letters and play for selected time.  Need to be able to select the group length (1 to 8).

4) Select a predetermined set of characters (like CW_Player lessons) and run for a selected time and group length.

5) Be able to put / . , ? and prosigns into the groups of 3 and play them randomly within each group.

Comment:  I like the way G4FON changes speed and farnsworth better than CW_Player.  It is more straight forward and I think easier for students to understand. I also like the G4FON "session length" option better than picking the "number of characters" to play in CW_Player.

On ther other hand, picking the letters you want to use is easier in CW_Player because you just type them in versus having to check the letters in G4FON's set up folder.

**Comment by RandyLoeb** [comment]
P.S. probably there is someone in the club with the ability (and patience) to record the player, and load the file into Audacity or some tool and see the waveform and make timing measurements etc.

Also I see on Phillips generator page he offers advanced controls over dit/dah and other timings, I just have not surfaced that functionality but we could in theory add it if indeed there are significant problems....
