### ISSUE TITLE
Clock Relocation

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#76]
I've been working through the first session and found that you can't see the clock on a laptop screen when you are looking at the Play/Stop Group line at the bottom.  Can the clock be put either to the right of the Shuffle tab or under the Custom Group tab so the instructor can see it while looking at the Play/Stop group?

**Comment by RandyLoeb** [comment]
@nolleto1 to save real estate I have put the estimated time on the play button. When you press play, the word "play" will disappear and you'll see the time passed and the estimate, so you can see how far along you are right on the play button. Give it a try in /dev/ area and let me know what you think
