### ISSUE TITLE
need to calculate-%-correct:  if I choose 2 or more items I got wrong and they are the exact same letter grouping (e.g., "ERA"), the first one counts it, then next one will un-count it, etc.  I wish it would NOT un-count, but keep the item missed once in the missed section.

### ISSUE THREAD

**Issue by jim72upson** [LongIslandCW/morsebrowser#80]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RandyLoeb** [comment]
@jim72upson I'll take a look at this, thanks.

**Comment by RandyLoeb** [comment]
@jim72upson in our beta environment there is now a fix for this, so long as you do not press the same letter group within a half second. You can test in beta https://longislandcw.github.io/morsebrowser/dev/

**Comment by jim72upson** [comment]
Hi Randy, thank you so much....I think it is much better at least in my
mind....I hope it makes sense to the team.

Here 2 'icing on the cake' thoughts....none of these are important to me
yet....so only work on these IF the team feels at this point it's worthy....

1)  It would be wonderful IF an overall %-correct could be calculated.  I
assume the program could add-up how many 'words' or character groupings
were presented........and now it knows how many I clicked on as incorrect
..simple math from there to calculate my %-correct....

2)  I've noticed that IF I go back to to pick another LESSON (example:  I
'warm-up' with REA/REA....but then I wish to practice REA/UWB), it might be
a good to have a 'reset' button available that would reset some of the
program's fields (presented 'words', counters, etc.) if they want
to....leaving WPM/Farnsworth etc. as they are....

FYI.....not sure what the team's thoughts 'workflow'......but I will be
asking tonight about it....as I struggled with the 'workflow' to determine
if I got the played 'words' correct or not.  I am trying to NOT use
paper/pencil so that I work on ICR/copy-behind from the get-go.....and the
only 'workflow' I came up with was to use a digital 'tape' recorder where I
speak the 'words' that I heard as they are played...and then I go back to
listen to what I said on the recorder and compare to the 'revealed'
words....at which time I click on the revealed 'word' if I missed it.  I
don't know how else to know if I am in the 80%-90% range....or more in the
70%-80% range...or 'worse'....and a workflow of some sort makes
sense....unless paper/pencil is the recommended approach...

Thanks again, I am really looking forward to this class...

73, Jim / AC3B

**Comment by sclitheroe** [comment]
Commenting on the % correct thing - my workflow in G4FON was always to calculate my error rate based on how many characters it sent, compared to marking my work.  I'd then log how many chars sent and how many wrong in Excel and graph my error rate - lets me see when I'm on the downside of the slope learning a new speed, meaning its time to up the rate.

So the thing I would _love_ isn't being able to click on the letter groups I got wrong, I just want to know the strlen() (sorry, old C coder ;) of the text that was sent, and I can record the results of my test in my excel.

My understanding of Koch's original intent was that keeping score and moving on when you hit 90% was important to ensure you were pushing forward, but also as a means of positive reinforcement; a beginner can go days or weeks with seemingly little progress, but if you chart it faithfully, you can literally see your brain improving - I attached a sample of what I do to keep track of how I'm doing, and thus why knowing how many characters sent is important

Should be a very simple thing to implement - you know how many characters are in the play section, its how you calculate the run time already :)

![error rate sample](https://user-images.githubusercontent.com/90072768/176081527-106082a6-1498-48b3-b491-8631d0799901.jpg)
