### ISSUE TITLE
Request function to toggle card display on/off

### ISSUE THREAD

**Issue by LongIslandCW** [LongIslandCW/morsebrowser#83]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RandyLoeb** [comment]
@LongIslandCW @MikePadron Where should the button go?

**Comment by LongIslandCW** [comment]
For now let's put it next to the LOOP tile.

On May 15, 2022, at 3:01 PM, RandyLoeb ***@***.***> wrote:


@LongIslandCW <https://github.com/LongIslandCW> @MikePadron <https://github.com/MikePadron> Where should the button go?

**Comment by RandyLoeb** [comment]
@LongIslandCW ok take a look and close if ok.

**Comment by MikePadron** [comment]
Randy,

After closer inspection, lets group CARD SIZE, REVEAL, TRAIL, and CARDS on/off please.

THANK YOU!!

Mike

On May 15, 2022, at 3:22 PM, LongIslandCW ***@***.***> wrote:


For now let's put it next to the LOOP tile.

On May 15, 2022, at 3:01 PM, RandyLoeb ***@***.***> wrote:


@LongIslandCW <https://github.com/LongIslandCW> @MikePadron <https://github.com/MikePadron> Where should the button go?
