### ISSUE TITLE
Clock

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#9]
Would like to see a clock that indicates how long the file/lesson has been running and resets when you start a new file.

**Comment by RandyLoeb** [comment]
Ok.

**Comment by nolleto1** [comment]
See you then.
Tom

**Comment by RandyLoeb** [comment]
@nolleto1  timer, which updates on the completion of each word, should be on /dev/ now. let me know if ok

**Comment by nolleto1** [comment]
I would prefer a clock that runs constantly but this will work if that is easiest.
